sudo: required
services:
    - docker

before_install:
  - docker build -t aaniket/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aaniket/react-test npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t aaniket/multi-client ./client
  - docker build -t aaniket/multi-nginx ./nginx
  - docker build -t aaniket/multi-server ./server
  - docker build -t aaniket/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aaniket/multi-client
  - docker push aaniket/multi-nginx
  - docker push aaniket/multi-worker
  - docker push aaniket/multi-server
  - 

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-651231324680
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
